---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Servicios de Google:
    - Gmail:
        href: https://gmail.com/
        description: Cliente de correo de Google
        icon: gmail.png
    - Drive:
        href: https://drive.google.com/
        description: Almacenamiento en nube de Google
        icon: google-drive.png
    - Calendario:
        href: https://calendar.google.com/
        description: Calendario de Google
        icon: google-calendar.png
    - Youtube:
        href: https://youtube.com/
        description: Plataforma de videos y Streaming
        icon: youtube.png
- Utilidades:
    - ChatGPT OpenAI:
        href: https://chat.openai.com/
        description: Chat GPT para consultas
        icon: chatgpt.png
    - Canva:
        href: https://www.canva.com/es_es/
        description: Edición de plantillas para presentaciones y gráficos.
        icon: /images/canva.png
- Monitoreo:

    - Calendario:
        icon: google-calendar.png
        widget:
          type: calendar

    - Traefik:
        icon: traefik.png
        href: http://traefik.alvaro.civica.lab:8081
        description: Proxy inverso de Traefik
        #server: localhost
        container: traefik
        widget:
          type: traefik
          url: http://traefik.alvaro.civica.lab:8080
          #url: http://172.24.0.5:8080
          #username: username # optional
          #password: password # optional

    - Uptime-Kuma:
        icon: uptime-kuma.png
        href: http://uptime.alvaro.civica.lab
        container: uptime-kuma
        widget:
          type: uptimekuma
          url: http://uptime.alvaro.civica.lab:3001
          slug: homepage
